[project]
name = "frontend"
version = "0.1.0"
description = "Streamlit frontend interface for TEG project providing user interaction and visualization"
requires-python = ">=3.11"
dependencies = [
    "python-dotenv>=1.1.0",
    "requests>=2.32.3",
    "streamlit>=1.45.1",
]
