[project]
name = "backend"
version = "0.1.0"
description = "Flask backend API service for TEG project handling business logic and data processing"
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.1",
    "python-dotenv>=1.1.0",
    "requests>=2.32.3",
]
